services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=basedb'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - '5433:5432'
    networks:
      - backend
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
      - '15671:15671'
      - '61613:61613'
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
      - backend

networks:
  backend:
    driver: bridge
